E-Mail Wahl streichen
fsr-de/docs pull request #31
Opened 2021-06-08 08:20 UTC by Mupico

E-Mail Wahlen rausgestrichen, dafür nochmal explizit Urnen- und Briefwahl als Möglichekeiten genannt
Co-authored-by: @ArminWel

2021-06-29 14:32 UTC, cedric-lorenz approved these changes

2021-07-06 19:17 UTC, SilvanVerhoeven approved these changes

2021-07-06 19:56 UTC, janno42 requested changes

2021-07-06 19:56 UTC, janno42 commented on wahlordnung.md
> +(4) Wenn eine Person sowohl per Briefwahl als auch per Wahlzettel abgestimmt hat, verfällt die Stimmabgabe aus der Briefwahl.
```suggestion
(4) Wenn eine Person sowohl per Briefwahl als auch per Urnenwahl abgestimmt hat, verfällt die Stimmabgabe aus der Briefwahl.
```

Auch bei einer Briefwahl wird per Wahlzettel abgestimmt, die Formulierung muss deswegen präzisiert werden.

2021-07-23 09:34 UTC, merged