Berücksichtigung der akademischen Weihnachtsferien
fsr-de/docs pull request #33
Opened 2022-12-22 12:33 UTC by frcroth

2022-12-22 14:03 UTC, DrEGZo approved these changes

2022-12-22 23:08 UTC, DrEGZo requested changes

2022-12-22 23:08 UTC, DrEGZo commented on geschaeftsordnung-fachschaftsrat.md
> +(1) Während der Vorlesungszeit soll gemäß Satzung der Fachschaft Digital Engineering jede Woche eine Sitzung stattfinden. In der vorlesungsfreien Zeit soll mindestens alle drei Wochen eine Sitzung st
*akademischen

2023-01-31 22:21 UTC, frcroth commented
In #32 integriert.

2023-01-31 22:21 UTC, closed without merging